application: adn-beers
version: 1
runtime: python27
api_version: 1
threadsafe: no


# In production, uncomment line below.
# default_expiration: "30d"


skip_files:
- ^(.*/)?app\.yaml
- ^(.*/)?app\.yml
- ^(.*/)?index\.yaml
- ^(.*/)?index\.yml
- ^(.*/)?#.*#
- ^(.*/)?.*~
- ^(.*/)?.*\.py[co]
- ^(.*/)?.*/RCS/.*
- ^(.*/)?\..*
- ^(.*/)?tests$


builtins:
- appstats: on
- remote_api: on



handlers:

- url: /remote_api
  script: $PYTHON_LIB/google/appengine/ext/remote_api/handler.py
  login: admin
  secure: always
  
- url: /apple-touch-icon\.png
  mime_type: image/png
  static_files: static/apple-touch-icon.png
  upload: static/apple-touch-icon.png
  secure: always
  
- url: /favicon\.ico
  mime_type: image/png
  static_files: static/favicon.ico
  upload: static/favicon.ico
  secure: always
  
- url: /(robots\.txt|humans\.txt|crossdomain\.xml)
  static_files: static/\1
  upload: static/(robots\.txt|humans\.txt|crossdomain\.xml)
  secure: always
  
- url: /img/(.*\.(gif|png|jpg))
  static_files: static/img/\1
  upload: static/img/(.*\.(gif|png|jpg))
  secure: always
  
- url: /styles/(.*\.css)
  mime_type: text/css
  static_files: static/styles/\1
  upload: static/styles/(.*\.css)
  secure: always
  
- url: /scripts/(.*\.js)
  mime_type: text/javascript
  static_files: static/scripts/\1
  upload: static/scripts/(.*\.js)
  secure: always
  
- url: /(.*\.html)
  mime_type: text/html
  static_files: static/index.html
  upload: static/(.*\.html)
  secure: always
  
- url: /.*
  script: bootstrap.py
  secure: always
  